CREATE DATABASE db;

USE db;

CREATE TABLE IF NOT EXISTS grupo(
id INT NOT NULL AUTO_INCREMENT,
descripcion VARCHAR(50),
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS planCuenta(
id INT  NOT NULL AUTO_INCREMENT,
codigo VARCHAR(10) NOT NULL,
idGrupo  INT NOT NULL,
descripcion VARCHAR(60) NOT NULL,
naturaleza CHAR(1) NOT NULL,
estado BOOL,
PRIMARY KEY(id),
FOREIGN KEY(idgrupo) REFERENCES grupo(id)
);
